#! /usr/bin/env python
# -*- coding: utf-8 -*-

            
"""
1. 对于数列a = [1,2,3,4,5] 
"""
a = [1,2,3,4,5] 
a[::2] = [1,3,5] a[::-2] = [5,3,1]


"""
2. 一行代码实现对列表a的偶数位的元素加3求和
"""
sum([x for x in a if a.index(x) % 2 ==0 and x != 1])